#!/bin/bash -ex
#
# Build AWS Lambda function ZIP file and upload to S3
#
# Usage: ./build-upload-aws-lambda-function S3BUCKET S3KEY
#
# For example:
# ./build-upload-aws-lambda-function run.alestic.com lambda/aws-lambda-site-generator-npm.zip
#

s3bucket=${1:?Specify target S3 bucket name}
s3key=${2:?Specify target S3 key}
target=s3://$s3bucket/$s3key

tmpdir=$(mktemp -d /tmp/lambda-XXXXXX)
zipfile=$tmpdir/lambda.zip

zip -r9 $zipfile index.py

# Install new node, npm, yarn
# https://gist.github.com/isaacs/579814
(
 cd $tmpdir
 mkdir node
 mkdir node-latest-install
 (
  cd node-latest-install
  curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
  ./configure --prefix=../node
  make -j8 install
  cd ../node
  PATH=$(pwd)/bin:$PATH
  cd lib
  npm install yarn
 )
 zip -r9y $zipfile node
)

# Upload ZIP file to S3
aws s3 cp --acl=public-read $zipfile $target

# Clean up
rm -r $tmpdir
